name: Frontend CI (Development Only)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '22.17.1'

jobs:
  # フロントエンド専用CI/CD
  test-and-build:
    name: Test & Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test:run

      - name: Generate test coverage
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/coverage-final.json
          flags: frontend
          name: frontend-coverage
        if: success()

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8000

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: .next
          retention-days: 7

  # セキュリティスキャン
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'

      - name: NPM Audit
        run: npm audit --audit-level=high

  # 本番環境準備完了まで無効化
  # deploy-production:
  #   name: Deploy to Vercel (DISABLED - Production not ready)
  #   runs-on: ubuntu-latest
  #   needs: [test-and-build, security-scan]
  #   if: false  # Disabled until production environment is ready

  # deploy-preview:
  #   name: Deploy Preview (DISABLED - Production not ready)
  #   runs-on: ubuntu-latest
  #   needs: [test-and-build]
  #   if: false  # Disabled until production environment is ready
